header-from: ./.config/header.md

version: ""

formatter: markdown table

name: terraform-aws-ecs-iam-role-builder

content: |-
  {{ .Header }}

  # terraform-aws-ecs-iam-role-builder
  
  GitHub: [StratusGrid/terraform-aws-ecs-iam-role-builder](https://github.com/StratusGrid/terraform-aws-ecs-iam-role-builder)

  This module helps create an iam role with or without a custom policy(ies). It adds cloudwatch log rights to IAM as well as being able to attach custom policies

  ---

  ## Example Usage:
  Create a default role with permissions for ssm and cloudwatch agent

  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```

  Create a role with custom permissions in addition to ssm and cloudwatch agent permissions
  
  ```hcl
  {{ include "examples/example2.tfnot" }}
  ```
  ---

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  ## Contributors
  - Chris Hurst [GenesisChris](https://github.com/GenesisChris)
  - Ivan Casco [ivancasco-sg](https://github.com/ivancasco-sg)
  - Jason Drouhard [jason-drouhard](https://github.com/jason-drouhard)
  - Juan Sanches [juansanchezv](https://github.com/juanssanchezv)

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - header
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
